<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * Creates the complaints table with all fields required for the
     * Complaint Management Subsystem of Portal Rasmi Pejabat Daerah Kulai.
     */
    public function up(): void
    {
        Schema::create('complaints', function (Blueprint $table) {
            $table->id();

            /*
            |--------------------------------------------------------------------------
            | Unique Record ID
            |--------------------------------------------------------------------------
            | A human-readable unique identifier (e.g., CMP-20260517-0001)
            | generated by the application for easy reference by users and admins.
            */
            $table->string('record_id')->unique();

            /*
            |--------------------------------------------------------------------------
            | User Relationship
            |--------------------------------------------------------------------------
            | Links the complaint to the registered user who submitted it.
            | On user deletion, all associated complaints are also removed.
            */
            $table->foreignId('user_id')
                  ->constrained('users')
                  ->cascadeOnDelete();

            /*
            |--------------------------------------------------------------------------
            | Complaint Details
            |--------------------------------------------------------------------------
            | description  : Detailed explanation of the issue reported.
            | location     : Physical location where the issue occurred.
            */
            $table->text('description');
            $table->string('location');

            /*
            |--------------------------------------------------------------------------
            | Attachments
            |--------------------------------------------------------------------------
            | JSON array storing public URLs or file paths of uploaded images/docs.
            | Nullable because a complaint may be submitted without attachments.
            */
            $table->json('attachments')->nullable();

            /*
            |--------------------------------------------------------------------------
            | AI-forecasted Category
            |--------------------------------------------------------------------------
            | Category automatically predicted by the Gemini API based on
            | the complaint description (e.g., Road Damage, Waste Management).
            */
            $table->string('ai_category');

            /*
            |--------------------------------------------------------------------------
            | Admin Response & Status
            |--------------------------------------------------------------------------
            | admin_response : The official reply written by an administrator.
            | status         : Current progress of the complaint lifecycle.
            */
            $table->text('admin_response')->nullable();
            $table->enum('status', ['Pending', 'In Progress', 'Resolved', 'Rejected'])
                  ->default('Pending');

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * Drops the complaints table if it exists.
     */
    public function down(): void
    {
        Schema::dropIfExists('complaints');
    }
};
